### ISSUE TITLE
Quick instructions are broken - martin_kuba.work_env role is missing

### ISSUE THREAD

**Issue by livenson** [CESNET/perun-ansible#132]
| => ansible-playbook -i inventories/prod site.yml
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change,
 but still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting
 deprecation_warnings=False in ansible.cfg.
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

ERROR! the role 'martin_kuba.work_env' was not found in /Users/ilja/workspace/perun-ansible/roles:/Users/ilja/workspace/perun-ansible/cesnet_roles:/Users/ilja/workspace/perun-ansible

The error appears to be in '/Users/ilja/workspace/perun-ansible/site.yml': line 33, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # This role will set working environment to a sensible state.
    - martin_kuba.work_env
      ^ here

**Comment by martin-kuba** [comment]
The quick instructions missed the line 
`git submodule update --init --recursive`
for actually downloading the git submodules. It is fixed now.

**Comment by livenson** [comment]
Still fails:

`TASK [martin_kuba.work_env : Set timezone] ***************************************************************************************************
fatal: [193.40.11.203]: FAILED! => {"changed": false, "cmd": "/usr/bin/timedatectl set-timezone Europe/Prague", "msg": "Failed to set time zone: The name org.freedesktop.PolicyKit1 was not provided by any .service files", "rc": 1, "stderr": "Failed to set time zone: The name org.freedesktop.PolicyKit1 was not provided by any .service files\n", "stderr_lines": ["Failed to set time zone: The name org.freedesktop.PolicyKit1 was not provided by any .service files"], "stdout": "", "stdout_lines": []}
`

**Comment by martin-kuba** [comment]
I can't reproduce it on a fresh Debian 10 machine started from the default Debian image for OpenStack. The error message says that it is not possible to run
```bash
/usr/bin/timedatectl set-timezone Europe/Prague
```
which is a standard command for setting timezone.

**Comment by livenson** [comment]
Ok, I've tried that on an older Debian9. Will retry later then on something newer.
